### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by maximpetrov** [kkkkkkkkkq/2048#1]
Некорректно складываются числа в строке: строка 2 2 2 2 должна превратиться в 4 4 0 0, а у Вас превращается в 4 0 4 0

**Comment by kkkkkkkkkq** [comment]
Исправил

**Comment by maximpetrov** [comment]
Теперь у Вас неправильно обрабатывается сдвиг влево и вверх для полностью заполненных рядов

**Comment by kkkkkkkkkq** [comment]
Действительно, упустил одну мелочь. Теперь работает

**Comment by maximpetrov** [comment]
Теперь работает, осталось защитить проект на занятии
